// Registry of the bundled poster cards in assets/titlecards/, generated by
// scripts/make-title-cards.mjs.
//
// Metro requires every require() path to be a static string literal, you
// cannot require(`./foo/${slug}.png`), so each card is listed explicitly.
// GuideItem carries a `posterKey` (not a URL) for these, because they are
// local assets: require() returns a module id (a number), and shipping them in
// the bundle means they render instantly and work offline, unlike the remote
// Visit Seoul photos used elsewhere.
//
// Why these exist at all: real posters and redrawn versions of them are
// copyrighted (and the actors' likenesses separately so). These are original
// one-sheet-style cards with no protected element, safe for a commercial
// release. See scripts/make-title-cards.mjs.
import type { ImageSourcePropType } from 'react-native';

export const TITLE_CARDS: Record<string, ImageSourcePropType> = {
  'kpop-demon-hunters': require('../assets/titlecards/kpop-demon-hunters.png'),
  parasite: require('../assets/titlecards/parasite.png'),
  'squid-game': require('../assets/titlecards/squid-game.png'),
  'reply-1988': require('../assets/titlecards/reply-1988.png'),
  'itaewon-class': require('../assets/titlecards/itaewon-class.png'),
  vincenzo: require('../assets/titlecards/vincenzo.png'),
  'our-beloved-summer': require('../assets/titlecards/our-beloved-summer.png'),
  'lovely-runner': require('../assets/titlecards/lovely-runner.png'),
  'queen-of-tears': require('../assets/titlecards/queen-of-tears.png'),
  goblin: require('../assets/titlecards/goblin.png'),
  'my-love-from-the-star': require('../assets/titlecards/my-love-from-the-star.png'),
  'all-of-us-are-dead': require('../assets/titlecards/all-of-us-are-dead.png'),
  'mr-sunshine': require('../assets/titlecards/mr-sunshine.png'),
  'the-glory': require('../assets/titlecards/the-glory.png'),
  'descendants-of-the-sun': require('../assets/titlecards/descendants-of-the-sun.png'),
  'crash-landing-on-you': require('../assets/titlecards/crash-landing-on-you.png'),
  'twenty-five-twenty-one': require('../assets/titlecards/twenty-five-twenty-one.png'),
  'extraordinary-attorney-woo': require('../assets/titlecards/extraordinary-attorney-woo.png'),
};

export const titleCard = (key?: string): ImageSourcePropType | undefined =>
  key ? TITLE_CARDS[key] : undefined;
